# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FRP-Test' do

pod 'ReactiveCocoa', '5.0.0-rc.1'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FRP-Test

  target 'FRP-TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FRP-TestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
